### ISSUE TITLE
Translation errors in Scratch translation tool

### ISSUE THREAD

**Issue by freyjaodds** [CodeClub/CodeClubWorld-Projects#69]
There are some differences in the scratch translation tool (jumpto.cc/scratch-translate) when compared to the translations in Scratch itself, meaning that our translated projects have incorrect instructions in the scratch blocks. 

Here's an example:
The tool translates "when this sprite clicked" to "al clickear este objeto", but scratch translates it to "al hacer clic en este objeto". It means that when translating projects in markdown, the scratch blocks will only build correctly if it's translated as per the translation tool, which is not the same as scratch itself (and the translation tool one is, according to our scratch translator, an awkward translation).

Examples are from this project: http://projects.codeclubworld.org/es-ES/02_scratch-2/01/Memoria.html

![screen shot 2015-09-02 at 12 49 53](https://cloud.githubusercontent.com/assets/12068455/9630341/93c3f8e2-5171-11e5-83ac-ed34cbd9e5a7.png)

![screen shot 2015-09-02 at 12 53 46](https://cloud.githubusercontent.com/assets/12068455/9630360/b38a216a-5171-11e5-9900-241682892308.png)

**Comment by martinpeck** [comment]
Closing this cos it was opened in the wrong place.
